# Generated by Django 4.2.7 on 2023-11-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'speciality', 'verbose_name_plural': 'specialties'},
        ),
    ]
