# Generated by Django 4.2.7 on 2023-11-04 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('license_number', models.CharField(max_length=40, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(help_text="Doctor's academic degree", max_length=255)),
                ('languages_spoken', models.CharField(help_text='Languages the doctor can speak', max_length=255)),
                ('department', models.CharField(help_text='Department the doctor belongs to', max_length=255)),
                ('consultation_hours', models.CharField(help_text='Available time slots for consultation', max_length=255)),
                ('is_consultant', models.BooleanField(default=False, help_text='Is the doctor a consultant?')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the doctor is verified.')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='doctors/verification_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.speciality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
